### ISSUE TITLE
Need some initial stories

### ISSUE THREAD

**Issue by bivvo** [SouthSoundDevelopers/CVPZ.WebUI#1]
@CarBar We need some initial stories for the UI.  What elements should we expect? Do we have any examples to use as a starting point? I understand the general concept of the application but need a little more information to finish setup.

What kind of authentication do we want to use?
Is this admin only?
Should we start at a search screen?
Should we start at a data entry screen?

**Comment by CarBar** [comment]
I would vote for authentication to be hooked to many providers i.e. Google, Facebook, Live, Linked in... A user should be able to hook more than one to their account but that could be a later story.

A good starting point would maybe be a user creates an account, and they can create their own resume(CV).

@McLeopold is working on the data model.

**Comment by bivvo** [comment]
Going to close out. Going to use the main CVPZ repo for issues.
